language: node_js
node_js:
  - "6"
before_script:
  - npm install
  - cp ./config/travis/dnb_tst2_app7_s1_wb_cert_key.pem ~
  - cp ./config/travis/dnb_tst2_app7_s1_wb_cert_pub.pem ~
script:
  - npm start &
  - sleep 10
  - npm test
